/**
 * Migration script to clean up Pro features for existing Starter accounts
 * Run this once after implementing strict plan-based feature control
 *
 * Usage:
 * npx ts-node src/scripts/cleanup-starter-pro-features.ts
 */

import mongoose from 'mongoose';
import Restaurant from '../models/Restaurant.model';
import User from '../models/User.model';
import logger from '../utils/logger';
import dotenv from 'dotenv';

// Load environment variables
dotenv.config();

async function cleanupStarterProFeatures() {
  try {
    // Connect to MongoDB
    const mongoUri = process.env.MONGODB_URI;
    if (!mongoUri) {
      throw new Error('MONGODB_URI is not defined in environment variables');
    }

    await mongoose.connect(mongoUri);
    logger.info('Connected to MongoDB');

    // Find all Starter plan restaurants that have Pro features
    // Starter plan is for self-service accounts with subscription.plan = 'starter'
    const starterRestaurants = await Restaurant.find({
      'subscription.plan': 'starter',
      accountType: 'self-service',
      $or: [
        { widgetConfig: { $exists: true, $ne: null } },
        { googleReviewLink: { $exists: true, $ne: null } },
        { publicSlug: { $exists: true, $ne: null } },
      ],
    });

    logger.info(`Found ${starterRestaurants.length} Starter restaurants with Pro features`);

    if (starterRestaurants.length === 0) {
      logger.info('No Starter restaurants with Pro features found. Migration complete.');
      await mongoose.disconnect();
      return;
    }

    let cleanedCount = 0;
    let serverAccountsDeleted = 0;

    // Process each restaurant
    for (const restaurant of starterRestaurants) {
      const updates: any = {};
      const featuresCleaned: string[] = [];

      // Check and clean widgetConfig
      if (restaurant.widgetConfig) {
        updates.widgetConfig = undefined;
        featuresCleaned.push('widgetConfig');
      }

      // Check and clean googleReviewLink
      if (restaurant.googleReviewLink) {
        updates.googleReviewLink = undefined;
        featuresCleaned.push('googleReviewLink');
      }

      // Check and clean publicSlug (keep the auto-generated one)
      if (restaurant.publicSlug) {
        // Note: publicSlug will be re-generated by the pre-save hook if set to undefined
        updates.publicSlug = undefined;
        featuresCleaned.push('publicSlug');
      }

      // Delete server accounts
      const deleteResult = await User.deleteMany({
        restaurantId: restaurant._id,
        role: 'server',
      });

      if (deleteResult.deletedCount > 0) {
        serverAccountsDeleted += deleteResult.deletedCount;
        featuresCleaned.push('serverAccounts');
      }

      // Apply updates if any features were cleaned
      if (Object.keys(updates).length > 0) {
        await Restaurant.updateOne({ _id: restaurant._id }, { $set: updates });
        cleanedCount++;
      }

      // Log details for each restaurant
      if (featuresCleaned.length > 0) {
        logger.info(
          `Cleaned up Pro features for restaurant ${restaurant.name} (${restaurant._id}):`,
          {
            restaurantId: restaurant._id.toString(),
            featuresCleaned,
            serverAccountsDeleted: deleteResult.deletedCount,
          }
        );
      }
    }

    logger.info(`Migration completed successfully:`);
    logger.info(`- Starter restaurants processed: ${starterRestaurants.length}`);
    logger.info(`- Restaurants cleaned: ${cleanedCount}`);
    logger.info(`- Server accounts deleted: ${serverAccountsDeleted}`);

    // Verify migration
    const verifyStarterWithWidget = await Restaurant.countDocuments({
      'subscription.plan': 'starter',
      widgetConfig: { $exists: true, $ne: null },
    });
    const verifyStarterWithGoogleReview = await Restaurant.countDocuments({
      'subscription.plan': 'starter',
      googleReviewLink: { $exists: true, $ne: null },
    });
    const verifyStarterWithCustomSlug = await Restaurant.countDocuments({
      'subscription.plan': 'starter',
      publicSlug: { $exists: true, $ne: null },
    });

    logger.info(`Post-migration verification:`);
    logger.info(`- Starter restaurants with widgetConfig: ${verifyStarterWithWidget}`);
    logger.info(`- Starter restaurants with googleReviewLink: ${verifyStarterWithGoogleReview}`);
    logger.info(`- Starter restaurants with custom slug: ${verifyStarterWithCustomSlug}`);

    await mongoose.disconnect();
    logger.info('Disconnected from MongoDB');
    process.exit(0);
  } catch (error) {
    logger.error('Migration failed:', error);
    process.exit(1);
  }
}

// Run migration
cleanupStarterProFeatures();
